---

- name: write rsa pub keys into a known_hosts hostname
  known_hosts: path='files/nodes/ssh_rsa_known_hosts'
               name='{{ item }}'
               key="{{ item }} {{ lookup('file', 'files/nodes/' + item + '/ssh/ssh_host_rsa_key.pub') }}"
  delegate_to: localhost
  with_items: groups.pxe_bootable_nodes

- name: write rsa pub keys into a known_hosts ip
  known_hosts: path='files/nodes/ssh_rsa_known_hosts'
               name='{{ hostvars[item].ip_address }}'
               key="{{ hostvars[item].ip_address }} {{ lookup('file', 'files/nodes/' + item + '/ssh/ssh_host_rsa_key.pub') }}"
  delegate_to: localhost
  with_items: groups.pxe_bootable_nodes

- name: write rsa pub keys into a known_hosts ibip
  known_hosts: path='files/nodes/ssh_rsa_known_hosts'
               name='{{ hostvars[item].ib_ip_addr }}'
               key="{{ hostvars[item].ib_ip_addr }} {{ lookup('file', 'files/nodes/' + item + '/ssh/ssh_host_rsa_key.pub') }}"
  delegate_to: localhost
  with_items: groups.pxe_bootable_nodes

- name: write ecdsa pub keys into a known_hosts hostname
  known_hosts: path='files/nodes/ssh_ecdsa_known_hosts'
               name='{{ item }}'
               key="{{ item }} {{ lookup('file', 'files/nodes/' + item + '/ssh/ssh_host_ecdsa_key.pub') }}"
  delegate_to: localhost
  with_items: groups.pxe_bootable_nodes

- name: write ecdsa pub keys into a known_hosts ip
  known_hosts: path='files/nodes/ssh_ecdsa_known_hosts'
               name='{{ hostvars[item].ip_address }}'
               key="{{ hostvars[item].ip_address }} {{ lookup('file', 'files/nodes/' + item + '/ssh/ssh_host_ecdsa_key.pub') }}"
  delegate_to: localhost
  with_items: groups.pxe_bootable_nodes

- name: write ecdsa pub keys into a known_hosts ibip
  known_hosts: path='files/nodes/ssh_ecdsa_known_hosts'
               name='{{ hostvars[item].ib_ip_addr }}'
               key="{{ hostvars[item].ib_ip_addr }} {{ lookup('file', 'files/nodes/' + item + '/ssh/ssh_host_ecdsa_key.pub') }}"
  delegate_to: localhost
  with_items: groups.pxe_bootable_nodes

- name: write ed25519 pub keys into a known_hosts hostname
  known_hosts: path='files/nodes/ssh_ed25519_known_hosts'
               name='{{ item }}'
               key="{{ item }} {{ lookup('file', 'files/nodes/' + item + '/ssh/ssh_host_ed25519_key.pub') }}"
  delegate_to: localhost
  with_items: groups.pxe_bootable_nodes

- name: write ed25519 pub keys into a known_hosts ip
  known_hosts: path='files/nodes/ssh_ed25519_known_hosts'
               name='{{ hostvars[item].ip_address }}'
               key="{{ hostvars[item].ip_address }} {{ lookup('file', 'files/nodes/' + item + '/ssh/ssh_host_ed25519_key.pub') }}"
  delegate_to: localhost
  with_items: groups.pxe_bootable_nodes

- name: write ed25519 pub keys into a known_hosts ibip
  known_hosts: path='files/nodes/ssh_ed25519_known_hosts'
               name='{{ hostvars[item].ib_ip_addr }}'
               key="{{ hostvars[item].ib_ip_addr }} {{ lookup('file', 'files/nodes/' + item + '/ssh/ssh_host_ed25519_key.pub') }}"
  delegate_to: localhost
  with_items: groups.pxe_bootable_nodes
